FROM node:22-alpine

ARG ROUTER_VERSION=latest
ARG OPENCLAW_VERSION=latest

RUN npm install -g openclaw@$OPENCLAW_VERSION

RUN npm install -g 9router@$ROUTER_VERSION 

EXPOSE 20128

ENTRYPOINT ["9router"]
